"""Bandcamp's discover genre / subgenre taxonomy.

GENERATED FILE - do not edit by hand. Regenerate with:

    python scripts/refresh_bandcamp_taxonomy.py

Every slug here is a valid ``tag_norm_names`` value for the discover API, so
what the user picks in the form is exactly what gets fetched. Subgenre slugs
are *not* globally unique (``folk`` is both a top-level genre and a subgenre of
``acoustic``), which is why lookups go through the helpers below rather than
assuming a flat unique key.
"""

GENRES: list[dict[str, str]] = [
    {"slug": "electronic", "label": "electronic"},
    {"slug": "rock", "label": "rock"},
    {"slug": "metal", "label": "metal"},
    {"slug": "alternative", "label": "alternative"},
    {"slug": "hip-hop-rap", "label": "hip-hop/rap"},
    {"slug": "experimental", "label": "experimental"},
    {"slug": "punk", "label": "punk"},
    {"slug": "folk", "label": "folk"},
    {"slug": "pop", "label": "pop"},
    {"slug": "ambient", "label": "ambient"},
    {"slug": "soundtrack", "label": "soundtrack"},
    {"slug": "world", "label": "world"},
    {"slug": "jazz", "label": "jazz"},
    {"slug": "acoustic", "label": "acoustic"},
    {"slug": "funk", "label": "funk"},
    {"slug": "r-b-soul", "label": "r&b/soul"},
    {"slug": "devotional", "label": "devotional"},
    {"slug": "classical", "label": "classical"},
    {"slug": "reggae", "label": "reggae"},
    {"slug": "podcasts", "label": "podcasts"},
    {"slug": "country", "label": "country"},
    {"slug": "spoken-word", "label": "spoken word"},
    {"slug": "comedy", "label": "comedy"},
    {"slug": "blues", "label": "blues"},
    {"slug": "kids", "label": "kids"},
    {"slug": "audiobooks", "label": "audiobooks"},
    {"slug": "latin", "label": "latin"},
]

SUBGENRES: list[dict[str, str]] = [
    {"slug": "folk", "label": "folk", "parent": "acoustic"},
    {"slug": "singer-songwriter", "label": "singer-songwriter", "parent": "acoustic"},
    {"slug": "rock", "label": "rock", "parent": "acoustic"},
    {"slug": "pop", "label": "pop", "parent": "acoustic"},
    {"slug": "guitar", "label": "guitar", "parent": "acoustic"},
    {"slug": "americana", "label": "americana", "parent": "acoustic"},
    {"slug": "electro-acoustic", "label": "electro-acoustic", "parent": "acoustic"},
    {"slug": "instrumental", "label": "instrumental", "parent": "acoustic"},
    {"slug": "piano", "label": "piano", "parent": "acoustic"},
    {"slug": "bluegrass", "label": "bluegrass", "parent": "acoustic"},
    {"slug": "roots", "label": "roots", "parent": "acoustic"},
    {"slug": "indie-rock", "label": "indie rock", "parent": "alternative"},
    {"slug": "industrial", "label": "industrial", "parent": "alternative"},
    {"slug": "shoegaze", "label": "shoegaze", "parent": "alternative"},
    {"slug": "grunge", "label": "grunge", "parent": "alternative"},
    {"slug": "goth", "label": "goth", "parent": "alternative"},
    {"slug": "dream-pop", "label": "dream pop", "parent": "alternative"},
    {"slug": "emo", "label": "emo", "parent": "alternative"},
    {"slug": "math-rock", "label": "math rock", "parent": "alternative"},
    {"slug": "britpop", "label": "britpop", "parent": "alternative"},
    {"slug": "jangle-pop", "label": "jangle pop", "parent": "alternative"},
    {"slug": "chill-out", "label": "chill-out", "parent": "ambient"},
    {"slug": "drone", "label": "drone", "parent": "ambient"},
    {"slug": "dark-ambient", "label": "dark ambient", "parent": "ambient"},
    {"slug": "electronic", "label": "electronic", "parent": "ambient"},
    {"slug": "soundscapes", "label": "soundscapes", "parent": "ambient"},
    {"slug": "field-recordings", "label": "field recordings", "parent": "ambient"},
    {"slug": "atmospheric", "label": "atmospheric", "parent": "ambient"},
    {"slug": "meditation", "label": "meditation", "parent": "ambient"},
    {"slug": "noise", "label": "noise", "parent": "ambient"},
    {"slug": "new-age", "label": "new age", "parent": "ambient"},
    {"slug": "idm", "label": "idm", "parent": "ambient"},
    {"slug": "industrial", "label": "industrial", "parent": "ambient"},
    {"slug": "rhythm-blues", "label": "rhythm & blues", "parent": "blues"},
    {"slug": "blues-rock", "label": "blues rock", "parent": "blues"},
    {"slug": "country-blues", "label": "country blues", "parent": "blues"},
    {"slug": "boogie-woogie", "label": "boogie-woogie", "parent": "blues"},
    {"slug": "delta-blues", "label": "delta blues", "parent": "blues"},
    {"slug": "americana", "label": "americana", "parent": "blues"},
    {"slug": "electric-blues", "label": "electric blues", "parent": "blues"},
    {"slug": "gospel", "label": "gospel", "parent": "blues"},
    {"slug": "bluegrass", "label": "bluegrass", "parent": "blues"},
    {"slug": "orchestral", "label": "orchestral", "parent": "classical"},
    {"slug": "neo-classical", "label": "neo-classical", "parent": "classical"},
    {"slug": "chamber-music", "label": "chamber music", "parent": "classical"},
    {"slug": "classical-piano", "label": "classical piano", "parent": "classical"},
    {"slug": "contemporary-classical", "label": "contemporary classical", "parent": "classical"},
    {"slug": "baroque", "label": "baroque", "parent": "classical"},
    {"slug": "opera", "label": "opera", "parent": "classical"},
    {"slug": "choral", "label": "choral", "parent": "classical"},
    {"slug": "modern-classical", "label": "modern classical", "parent": "classical"},
    {"slug": "avant-garde", "label": "avant garde", "parent": "classical"},
    {"slug": "improv", "label": "improv", "parent": "comedy"},
    {"slug": "stand-up", "label": "stand-up", "parent": "comedy"},
    {"slug": "bluegrass", "label": "bluegrass", "parent": "country"},
    {"slug": "country-rock", "label": "country rock", "parent": "country"},
    {"slug": "americana", "label": "americana", "parent": "country"},
    {"slug": "country-folk", "label": "country folk", "parent": "country"},
    {"slug": "alt-country", "label": "alt-country", "parent": "country"},
    {"slug": "country-blues", "label": "country blues", "parent": "country"},
    {"slug": "western", "label": "western", "parent": "country"},
    {"slug": "singer-songwriter", "label": "singer-songwriter", "parent": "country"},
    {"slug": "outlaw", "label": "outlaw", "parent": "country"},
    {"slug": "honky-tonk", "label": "honky-tonk", "parent": "country"},
    {"slug": "roots", "label": "roots", "parent": "country"},
    {"slug": "hillbilly", "label": "hillbilly", "parent": "country"},
    {"slug": "christian", "label": "christian", "parent": "devotional"},
    {"slug": "gospel", "label": "gospel", "parent": "devotional"},
    {"slug": "meditation", "label": "meditation", "parent": "devotional"},
    {"slug": "spiritual", "label": "spiritual", "parent": "devotional"},
    {"slug": "worship", "label": "worship", "parent": "devotional"},
    {"slug": "inspirational", "label": "inspirational", "parent": "devotional"},
    {"slug": "house", "label": "house", "parent": "electronic"},
    {"slug": "electronica", "label": "electronica", "parent": "electronic"},
    {"slug": "downtempo", "label": "downtempo", "parent": "electronic"},
    {"slug": "techno", "label": "techno", "parent": "electronic"},
    {"slug": "electro", "label": "electro", "parent": "electronic"},
    {"slug": "dubstep", "label": "dubstep", "parent": "electronic"},
    {"slug": "beats", "label": "beats", "parent": "electronic"},
    {"slug": "dance", "label": "dance", "parent": "electronic"},
    {"slug": "idm", "label": "idm", "parent": "electronic"},
    {"slug": "drum-bass", "label": "drum & bass", "parent": "electronic"},
    {"slug": "breaks", "label": "breaks", "parent": "electronic"},
    {"slug": "trance", "label": "trance", "parent": "electronic"},
    {"slug": "glitch", "label": "glitch", "parent": "electronic"},
    {"slug": "chiptune", "label": "chiptune", "parent": "electronic"},
    {"slug": "chillwave", "label": "chillwave", "parent": "electronic"},
    {"slug": "dub", "label": "dub", "parent": "electronic"},
    {"slug": "edm", "label": "edm", "parent": "electronic"},
    {"slug": "instrumental", "label": "instrumental", "parent": "electronic"},
    {"slug": "witch-house", "label": "witch house", "parent": "electronic"},
    {"slug": "garage", "label": "garage", "parent": "electronic"},
    {"slug": "juke", "label": "juke", "parent": "electronic"},
    {"slug": "footwork", "label": "footwork", "parent": "electronic"},
    {"slug": "vaporwave", "label": "vaporwave", "parent": "electronic"},
    {"slug": "synthwave", "label": "synthwave", "parent": "electronic"},
    {"slug": "noise", "label": "noise", "parent": "experimental"},
    {"slug": "drone", "label": "drone", "parent": "experimental"},
    {"slug": "avant-garde", "label": "avant garde", "parent": "experimental"},
    {"slug": "experimental-rock", "label": "experimental rock", "parent": "experimental"},
    {"slug": "improvisation", "label": "improvisation", "parent": "experimental"},
    {"slug": "sound-art", "label": "sound art", "parent": "experimental"},
    {"slug": "musique-concrete", "label": "musique concrete", "parent": "experimental"},
    {"slug": "singer-songwriter", "label": "singer-songwriter", "parent": "folk"},
    {"slug": "folk-rock", "label": "folk rock", "parent": "folk"},
    {"slug": "indie-folk", "label": "indie folk", "parent": "folk"},
    {"slug": "pop-folk", "label": "pop folk", "parent": "folk"},
    {"slug": "traditional", "label": "traditional", "parent": "folk"},
    {"slug": "experimental-folk", "label": "experimental folk", "parent": "folk"},
    {"slug": "roots", "label": "roots", "parent": "folk"},
    {"slug": "funk-jam", "label": "funk jam", "parent": "funk"},
    {"slug": "deep-funk", "label": "deep funk", "parent": "funk"},
    {"slug": "funk-rock", "label": "funk rock", "parent": "funk"},
    {"slug": "jazz-funk", "label": "jazz funk", "parent": "funk"},
    {"slug": "boogie", "label": "boogie", "parent": "funk"},
    {"slug": "g-funk", "label": "g-funk", "parent": "funk"},
    {"slug": "rare-groove", "label": "rare groove", "parent": "funk"},
    {"slug": "electro", "label": "electro", "parent": "funk"},
    {"slug": "go-go", "label": "go-go", "parent": "funk"},
    {"slug": "rap", "label": "rap", "parent": "hip-hop-rap"},
    {"slug": "underground-hip-hop", "label": "underground hip-hop", "parent": "hip-hop-rap"},
    {"slug": "instrumental-hip-hop", "label": "instrumental hip-hop", "parent": "hip-hop-rap"},
    {"slug": "trap", "label": "trap", "parent": "hip-hop-rap"},
    {"slug": "conscious-hip-hop", "label": "conscious hip-hop", "parent": "hip-hop-rap"},
    {"slug": "boom-bap", "label": "boom-bap", "parent": "hip-hop-rap"},
    {"slug": "beat-tape", "label": "beat-tape", "parent": "hip-hop-rap"},
    {"slug": "hardcore", "label": "hardcore", "parent": "hip-hop-rap"},
    {"slug": "grime", "label": "grime", "parent": "hip-hop-rap"},
    {"slug": "fusion", "label": "fusion", "parent": "jazz"},
    {"slug": "big-band", "label": "big band", "parent": "jazz"},
    {"slug": "nu-jazz", "label": "nu jazz", "parent": "jazz"},
    {"slug": "modern-jazz", "label": "modern jazz", "parent": "jazz"},
    {"slug": "swing", "label": "swing", "parent": "jazz"},
    {"slug": "free-jazz", "label": "free jazz", "parent": "jazz"},
    {"slug": "soul-jazz", "label": "soul jazz", "parent": "jazz"},
    {"slug": "latin-jazz", "label": "latin jazz", "parent": "jazz"},
    {"slug": "vocal-jazz", "label": "vocal jazz", "parent": "jazz"},
    {"slug": "bebop", "label": "bebop", "parent": "jazz"},
    {"slug": "spiritual-jazz", "label": "spiritual jazz", "parent": "jazz"},
    {"slug": "family-music", "label": "family music", "parent": "kids"},
    {"slug": "educational", "label": "educational", "parent": "kids"},
    {"slug": "music-therapy", "label": "music therapy", "parent": "kids"},
    {"slug": "lullaby", "label": "lullaby", "parent": "kids"},
    {"slug": "baby", "label": "baby", "parent": "kids"},
    {"slug": "brazilian", "label": "brazilian", "parent": "latin"},
    {"slug": "cumbia", "label": "cumbia", "parent": "latin"},
    {"slug": "tango", "label": "tango", "parent": "latin"},
    {"slug": "latin-rock", "label": "latin rock", "parent": "latin"},
    {"slug": "flamenco", "label": "flamenco", "parent": "latin"},
    {"slug": "salsa", "label": "salsa", "parent": "latin"},
    {"slug": "reggaeton", "label": "reggaeton", "parent": "latin"},
    {"slug": "merengue", "label": "merengue", "parent": "latin"},
    {"slug": "bolero", "label": "bolero", "parent": "latin"},
    {"slug": "méxico-d.f.", "label": "méxico d.f.", "parent": "latin"},
    {"slug": "bachata", "label": "bachata", "parent": "latin"},
    {"slug": "hardcore", "label": "hardcore", "parent": "metal"},
    {"slug": "black-metal", "label": "black metal", "parent": "metal"},
    {"slug": "death-metal", "label": "death metal", "parent": "metal"},
    {"slug": "thrash-metal", "label": "thrash metal", "parent": "metal"},
    {"slug": "grindcore", "label": "grindcore", "parent": "metal"},
    {"slug": "doom", "label": "doom", "parent": "metal"},
    {"slug": "post-hardcore", "label": "post hardcore", "parent": "metal"},
    {"slug": "progressive-metal", "label": "progressive metal", "parent": "metal"},
    {"slug": "metalcore", "label": "metalcore", "parent": "metal"},
    {"slug": "sludge-metal", "label": "sludge metal", "parent": "metal"},
    {"slug": "heavy-metal", "label": "heavy metal", "parent": "metal"},
    {"slug": "deathcore", "label": "deathcore", "parent": "metal"},
    {"slug": "noise", "label": "noise", "parent": "metal"},
    {"slug": "indie-pop", "label": "indie pop", "parent": "pop"},
    {"slug": "synth-pop", "label": "synth pop", "parent": "pop"},
    {"slug": "power-pop", "label": "power pop", "parent": "pop"},
    {"slug": "new-wave", "label": "new wave", "parent": "pop"},
    {"slug": "dream-pop", "label": "dream pop", "parent": "pop"},
    {"slug": "noise-pop", "label": "noise pop", "parent": "pop"},
    {"slug": "experimental-pop", "label": "experimental pop", "parent": "pop"},
    {"slug": "electro-pop", "label": "electro pop", "parent": "pop"},
    {"slug": "adult-contemporary", "label": "adult contemporary", "parent": "pop"},
    {"slug": "jangle-pop", "label": "jangle pop", "parent": "pop"},
    {"slug": "j-pop", "label": "j-pop", "parent": "pop"},
    {"slug": "hardcore-punk", "label": "hardcore punk", "parent": "punk"},
    {"slug": "garage", "label": "garage", "parent": "punk"},
    {"slug": "pop-punk", "label": "pop punk", "parent": "punk"},
    {"slug": "punk-rock", "label": "punk rock", "parent": "punk"},
    {"slug": "post-punk", "label": "post-punk", "parent": "punk"},
    {"slug": "post-hardcore", "label": "post-hardcore", "parent": "punk"},
    {"slug": "thrash", "label": "thrash", "parent": "punk"},
    {"slug": "crust-punk", "label": "crust punk", "parent": "punk"},
    {"slug": "folk-punk", "label": "folk punk", "parent": "punk"},
    {"slug": "emo", "label": "emo", "parent": "punk"},
    {"slug": "ska", "label": "ska", "parent": "punk"},
    {"slug": "no-wave", "label": "no wave", "parent": "punk"},
    {"slug": "soul", "label": "soul", "parent": "r-b-soul"},
    {"slug": "r-b", "label": "r&b", "parent": "r-b-soul"},
    {"slug": "neo-soul", "label": "neo-soul", "parent": "r-b-soul"},
    {"slug": "gospel", "label": "gospel", "parent": "r-b-soul"},
    {"slug": "contemporary-r-b", "label": "contemporary r&b", "parent": "r-b-soul"},
    {"slug": "motown", "label": "motown", "parent": "r-b-soul"},
    {"slug": "urban", "label": "urban", "parent": "r-b-soul"},
    {"slug": "dub", "label": "dub", "parent": "reggae"},
    {"slug": "ska", "label": "ska", "parent": "reggae"},
    {"slug": "roots", "label": "roots", "parent": "reggae"},
    {"slug": "dancehall", "label": "dancehall", "parent": "reggae"},
    {"slug": "rocksteady", "label": "rocksteady", "parent": "reggae"},
    {"slug": "ragga", "label": "ragga", "parent": "reggae"},
    {"slug": "lovers-rock", "label": "lovers rock", "parent": "reggae"},
    {"slug": "indie", "label": "indie", "parent": "rock"},
    {"slug": "prog-rock", "label": "prog rock", "parent": "rock"},
    {"slug": "post-rock", "label": "post-rock", "parent": "rock"},
    {"slug": "rock-roll", "label": "rock & roll", "parent": "rock"},
    {"slug": "psychedelic-rock", "label": "psychedelic rock", "parent": "rock"},
    {"slug": "hard-rock", "label": "hard rock", "parent": "rock"},
    {"slug": "garage-rock", "label": "garage rock", "parent": "rock"},
    {"slug": "surf-rock", "label": "surf rock", "parent": "rock"},
    {"slug": "instrumental", "label": "instrumental", "parent": "rock"},
    {"slug": "math-rock", "label": "math rock", "parent": "rock"},
    {"slug": "rockabilly", "label": "rockabilly", "parent": "rock"},
    {"slug": "film-music", "label": "film music", "parent": "soundtrack"},
    {"slug": "video-game-music", "label": "video game music", "parent": "soundtrack"},
    {"slug": "video-game", "label": "video game", "parent": "soundtrack"},
    {"slug": "ost", "label": "ost", "parent": "soundtrack"},
    {"slug": "poetry", "label": "poetry", "parent": "spoken-word"},
    {"slug": "inspirational", "label": "inspirational", "parent": "spoken-word"},
    {"slug": "storytelling", "label": "storytelling", "parent": "spoken-word"},
    {"slug": "self-help", "label": "self-help", "parent": "spoken-word"},
    {"slug": "latin", "label": "latin", "parent": "world"},
    {"slug": "roots", "label": "roots", "parent": "world"},
    {"slug": "african", "label": "african", "parent": "world"},
    {"slug": "tropical", "label": "tropical", "parent": "world"},
    {"slug": "tribal", "label": "tribal", "parent": "world"},
    {"slug": "brazilian", "label": "brazilian", "parent": "world"},
    {"slug": "celtic", "label": "celtic", "parent": "world"},
    {"slug": "world-fusion", "label": "world fusion", "parent": "world"},
    {"slug": "cumbia", "label": "cumbia", "parent": "world"},
    {"slug": "gypsy", "label": "gypsy", "parent": "world"},
    {"slug": "new-age", "label": "new age", "parent": "world"},
    {"slug": "balkan", "label": "balkan", "parent": "world"},
    {"slug": "reggaeton", "label": "reggaeton", "parent": "world"},
]


# Flat set of every slug the discover API will accept, for O(1) validation.
KNOWN_SLUGS: frozenset[str] = frozenset([g["slug"] for g in GENRES] + [s["slug"] for s in SUBGENRES])


def is_known(slug: str) -> bool:
    """True if ``slug`` is part of Bandcamp's discover taxonomy."""
    return slug.strip().lower() in KNOWN_SLUGS


def subgenres_for(genre_slug: str) -> list[dict[str, str]]:
    """Subgenres nested under a top-level genre, in Bandcamp's own order."""
    return [s for s in SUBGENRES if s["parent"] == genre_slug]


def as_picker_payload() -> dict:
    """Taxonomy shaped for the browser picker: genres, each with its subgenres."""
    return {"genres": [{"slug": g["slug"], "label": g["label"], "subgenres": subgenres_for(g["slug"])} for g in GENRES]}
